name: deploy-backend

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
      with:
        clean: false

    # Down Docker-compose container
    - name: Stop and Remove Container
      run: |
        docker compose down -v
      
    # Start Docker-compose
    - name: Start Docker Container
      run: docker compose up -d
