name: deploy-backend

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
    
    # Down Docker-compose container
    - name: Stop Docker Containers
      run: docker compose down
      
    # Delete Docker Images (Frontend, Backend)
    - name: Remove Backend Image
      run: docker rmi work-backapp

    # Fetch latest version from branch dev 
    - name: Fetching Latest Data
      run: git fetch
      
    # Pull from Github 
    - name: Pulling Latest Data
      run: git pull
          
    # Start Docker-compose
    - name: Start Docker Container
      run: docker compose up -d
